# Generated by Django 5.1.1 on 2024-10-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidal_phase', models.CharField(max_length=50)),
                ('salinity', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('wind_direction', models.CharField(max_length=10)),
                ('wind_speed', models.IntegerField()),
                ('secchi_depth', models.IntegerField()),
                ('fu_scale', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('fishingday', models.IntegerField()),
                ('fyke', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('collect', models.IntegerField()),
                ('remarks', models.TextField()),
                ('observer', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fyke_datacollection',
            },
        ),
    ]
