# Generated by Django 5.1.1 on 2024-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchlocations',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Fyke name'),
        ),
        migrations.AlterField(
            model_name='catchlocations',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Type'),
        ),
        migrations.AlterModelTable(
            name='catchlocations',
            table='fyke_catchlocations',
        ),
    ]
