# Generated by Django 5.1.1 on 2024-10-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='fyke',
            field=models.CharField(choices=[('Stuifdijk', 'Stuifdijk'), ('Afsluitdijk', 'Afsluitdijk'), ('Schanserwaard', 'Schanserwaard'), ('Pakeerplaats NIOZ achter', 'Pakeerplaats NIOZ achter'), ('Parkeerplaats haven', 'Parkeerplaats haven'), ('Texelstroom', 'Texelstroom'), ('NIOZ dam', 'NIOZ dam'), ('Navicula', 'Navicula'), ('Wierbalg', 'Wierbalg'), ('WMR-NIOZ otoliths project', 'WMR-NIOZ otoliths project'), ('Gat v Stier', 'Gat v Stier'), ('HW-prog', 'HW-prog'), ('IJhaven Amsterdam', 'IJhaven Amsterdam'), ('NA', 'NA'), ('NIOZ_Harbour', 'NIOZ_Harbour'), ('North Sea', 'North Sea'), ('Terschelling', 'Terschelling'), ('Texelstroom', 'Texelstroom'), ('WaddenSea', 'WaddenSea'), ('Texel beach', 'Texel beach'), ('Fyke Sieme', 'Fyke Sieme'), ('Eems', 'Eems'), ('Dooie Hond', 'Dooie Hond'), ('Eerste hoofd', 'Eerste hoofd'), ('Veerhaven', 'Veerhaven'), ('Hors', 'Hors'), ('Schanderwaard', 'Schanderwaard'), ('Vlettenstelling', 'Vlettenstelling'), ('Hoek van de staak', 'Hoek van de staak'), ('Onbekend', 'Onbekend'), ('Schiermonnikoog', 'Schiermonnikoog'), ('Borkumse stenen', 'Borkumse stenen')], max_length=100),
        ),
    ]
