# Generated by Django 5.1.1 on 2024-10-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0002_alter_datacollection_fyke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='week',
        ),
    ]
