# Generated by Django 5.1.1 on 2024-10-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0003_remove_datacollection_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='year',
        ),
    ]
