# Generated by Django 5.1.1 on 2024-10-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0004_remove_datacollection_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='fu_scale',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='observer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='salinity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='secchi_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='tidal_phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='wind_direction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='wind_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
