# Generated by Django 5.1.1 on 2024-10-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0005_alter_datacollection_fu_scale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FykeLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=256)),
                ('collectgroup', models.CharField(max_length=50)),
                ('printlabel', models.CharField(max_length=50)),
                ('latitude', models.FloatField(choices=[('Texel', 'Texel'), ('Lauwersoog', 'Lauwersoog')])),
                ('longitude', models.FloatField(choices=[('Texel', 'Texel'), ('Lauwersoog', 'Lauwersoog')])),
            ],
            options={
                'db_table': 'fyke_fykelocations',
            },
        ),
    ]
