# Generated by Django 5.1.1 on 2024-10-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0006_fykelocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectdate', models.DateField(blank=True, null=True)),
                ('registrationtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('collectno', models.IntegerField(blank=True, null=True)),
                ('species', models.CharField(blank=True, max_length=50, null=True)),
                ('total_length', models.IntegerField(blank=True, null=True)),
                ('fork_length', models.IntegerField(blank=True, null=True)),
                ('standard_length', models.IntegerField(blank=True, null=True)),
                ('fresh_weight', models.IntegerField(blank=True, null=True)),
                ('total_wet_mass', models.IntegerField(blank=True, null=True)),
                ('stomach_content', models.CharField(blank=True, max_length=255, null=True)),
                ('gonad_mass', models.IntegerField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=50, null=True)),
                ('ripeness', models.IntegerField(blank=True, null=True)),
                ('otolith', models.CharField(blank=True, max_length=50, null=True)),
                ('isotopeflag', models.IntegerField(blank=True, null=True)),
                ('total_length_frozen', models.IntegerField(blank=True, null=True)),
                ('fork_length_frozen', models.IntegerField(blank=True, null=True)),
                ('standard_length_frozen', models.IntegerField(blank=True, null=True)),
                ('frozen_mass', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('rings', models.IntegerField(blank=True, null=True)),
                ('ogew1', models.CharField(blank=True, max_length=50, null=True)),
                ('ogew2', models.CharField(blank=True, max_length=50, null=True)),
                ('tissue_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vial', models.CharField(blank=True, max_length=50, null=True)),
                ('dna_sample', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('micro_plastic', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fyke_fishdetails',
            },
        ),
    ]
