# Generated by Django 5.1.1 on 2024-11-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0007_fishdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishdetails',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
