# Generated by Django 5.1.1 on 2024-11-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0008_fishdetails_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishdetails',
            name='fork_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishdetails',
            name='fork_length_frozen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishdetails',
            name='fresh_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishdetails',
            name='frozen_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishdetails',
            name='gonad_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishdetails',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishdetails',
            name='standard_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishdetails',
            name='standard_length_frozen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishdetails',
            name='total_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishdetails',
            name='total_length_frozen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishdetails',
            name='total_wet_mass',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
