# Generated by Django 5.1.1 on 2024-11-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0009_alter_fishdetails_fork_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishdetails',
            name='liver_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
