# Generated by Django 5.1.1 on 2024-11-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0010_fishdetails_liver_weight'),
        ('fyke', '0011_datacollection_changed_by_datacollection_last_change'),
    ]

    operations = [
    ]
