# Generated by Django 5.1.1 on 2024-11-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0012_merge_20241129_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishdetails',
            name='changed_by',
        ),
    ]
