# Generated by Django 5.1.1 on 2024-12-03 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0013_remove_fishdetails_changed_by'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishdetails',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_collections', to='maintenance.maintenancespecieslist'),
            preserve_default=False,
        ),
    ]
