# Generated by Django 5.1.1 on 2024-12-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0013_remove_fishdetails_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='collect',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='duration',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='fishingday',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='fu_scale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='salinity',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='secchi_depth',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='temperature',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='tidal_phase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='version',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='wind_direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='wind_speed',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
