# Generated by Django 5.1.1 on 2024-09-30 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('active', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[01]$', 'Only "0" or "1" are allowed.')])),
                ('realName', models.CharField(max_length=50)),
                ('collectlocation', models.CharField(max_length=50)),
                ('yearFrom', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.')])),
                ('yearUntil', models.CharField(max_length=10)),
            ],
        ),
    ]
