# Generated by Django 5.1.1 on 2024-10-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0002_alter_person_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='active',
        ),
    ]
