# Generated by Django 5.1.1 on 2024-10-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0003_buttonstate_remove_person_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ButtonState',
        ),
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
