# Generated by Django 5.1.1 on 2024-10-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0005_person_accesslauwersoog_person_accesstexel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texel', models.IntegerField()),
                ('lauwersoog', models.IntegerField()),
            ],
        ),
    ]
