# Generated by Django 5.1.1 on 2024-10-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0006_accesschoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessChoice',
        ),
    ]
