# Generated by Django 5.1.1 on 2024-10-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0008_alter_person_accesslauwersoog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
