# Generated by Django 5.1.1 on 2024-10-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0009_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='accessTexel',
            field=models.IntegerField(default=None),
        ),
    ]
