# Generated by Django 5.1.1 on 2024-10-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0010_alter_person_accesstexel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='accessTexel',
            field=models.IntegerField(default=3),
        ),
    ]
