# Generated by Django 5.1.1 on 2024-10-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0011_alter_person_accesstexel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='accessLauwersoog',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='deleteRecords',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='fishdata',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='fishdataExport',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='fishdataRecords',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='fishdataSource',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='fyke',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='fykeBioticdata',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='fykeDatacollection',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='fykeExportdata',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='fykeFishDetails',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='fykeLocations',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='help',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='maintenance',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='maintenanceFishprogrammes',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='maintenanceLocations',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='maintenanceSpecies',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='manager',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='managerUserAccess',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='options',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='optionsUserSettings',
            field=models.IntegerField(default=3),
        ),
    ]
