# Generated by Django 5.1.1 on 2024-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0012_alter_person_accesslauwersoog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='collectlocation',
            field=models.CharField(default='Texel (RW) Lauwersoog (RW)', max_length=100),
        ),
    ]
