# Generated by Django 5.1.1 on 2024-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0013_alter_person_collectlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='yearFrom',
            field=models.CharField(default='2024', max_length=10),
        ),
    ]
