# Generated by Django 5.1.1 on 2024-10-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0014_alter_person_yearfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='yearUntil',
            field=models.CharField(default=9999, max_length=4),
        ),
    ]
