# Generated by Django 5.1.1 on 2024-10-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0015_alter_person_yearuntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
