# Generated by Django 5.1.1 on 2024-11-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0016_alter_person_password_alter_person_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='active',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
