# Generated by Django 5.1.1 on 2024-11-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0018_person_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Mens', 'verbose_name_plural': 'Mensen'},
        ),
        migrations.AlterModelTable(
            name='person',
            table='adminmenu_person',
        ),
    ]
