# Generated by Django 5.1.1 on 2024-11-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0019_alter_person_options_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Gebruiker', 'verbose_name_plural': 'Gebruikers'},
        ),
    ]
