# Generated by Django 5.1.1 on 2024-12-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FykeLocation',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=254)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fyke Location',
                'verbose_name_plural': 'Fyke Locations',
                'db_table': 'fyke_locations',
            },
        ),
        migrations.CreateModel(
            name='FykeProgramme',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('programme', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fyke Programme',
                'verbose_name_plural': 'Fyke Programmes',
                'db_table': 'fyke_programmes',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSpeciesList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('species_id', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('nl_name', models.CharField(max_length=255)),
                ('en_name', models.CharField(max_length=255)),
                ('latin_name', models.CharField(max_length=255)),
                ('WoRMS', models.CharField(max_length=255)),
                ('pauly_trophic_level', models.FloatField()),
                ('var_x', models.TextField(blank=True, null=True)),
                ('fishflag', models.BooleanField(default=False)),
                ('collecting_per_week', models.IntegerField()),
                ('always_collecting', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Species list',
                'verbose_name_plural': 'Species list',
                'db_table': 'maintenance_species_list',
            },
        ),
    ]
