# Generated by Django 5.0.6 on 2024-10-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSpeciesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('nl_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('latin_name', models.CharField(max_length=255)),
                ('WoRMS', models.CharField(max_length=255)),
                ('pauly_trophic_level', models.IntegerField()),
                ('var_x', models.TextField()),
                ('fishflag', models.BooleanField(default=False)),
                ('collecting_per_week', models.IntegerField()),
                ('always_collecting', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'maintenance_species_list',
            },
        ),
    ]
