# Generated by Django 5.0.6 on 2024-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fykelocation',
            name='location',
            field=models.CharField(max_length=254),
        ),
    ]
