# Generated by Django 5.0.6 on 2024-10-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancespecieslist',
            name='pauly_trophic_level',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='maintenancespecieslist',
            name='var_x',
            field=models.TextField(blank=True, null=True),
        ),
    ]
