# Generated by Django 5.0.6 on 2024-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenancespecieslist_always_collecting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancespecieslist',
            name='always_collecting',
            field=models.BooleanField(default=True),
        ),
    ]
