# Generated by Django 5.0.6 on 2024-10-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenancespecieslist_pauly_trophic_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancespecieslist',
            name='species_id',
            field=models.IntegerField(null=True),
        ),
    ]
