# Generated by Django 5.0.6 on 2024-10-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancespecieslist_species_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancespecieslist',
            name='species_id',
            field=models.IntegerField(default=0),
        ),
    ]
