# Generated by Django 5.0.6 on 2024-11-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancespecieslist_always_collecting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FykeLocation',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fyke Location',
                'verbose_name_plural': 'Fyke Locations',
                'db_table': 'fyke_locations',
            },
        ),
        migrations.CreateModel(
            name='FykeProgramme',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('programme', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fyke Programme',
                'verbose_name_plural': 'Fyke Programmes',
                'db_table': 'fyke_programmes',
            },
        ),
    ]
