# Generated by Django 5.1.1 on 2024-11-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenancespecieslist_species_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancespecieslist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintenancespecieslist',
            name='species_id',
            field=models.IntegerField(),
        ),
    ]
